### ISSUE TITLE
D3 Example

### ISSUE THREAD

**Issue by mrkjones1979** [sassoftware/sas-visualanalytics-thirdpartyvisualizations#1]
Hi,

Thanks for the C3 and Google Chart examples, they are very useful for someone like me with limited knowledge of JavaScript.

I am struggling with how to apply the techniques in the examples to D3 (again limited JavaScript knowledge being the issue!)  Any chance of replicating the simple C3 bar chart example with D3?

Many thanks in advance.

**Comment by rluppi** [comment]
Hi @mrkjones1979 ,

Sorry for the delay. We have added a D3 bar chart example that although simple, it is quite complete as it supports default visualization (sample chart as template), data formatting, window resizing, selections (brushing), roles assignment validation, and other things that should always be considered, besides just visualizing the data.

Thanks
