### ISSUE TITLE
messagingUtil.postSelectionMessage: filter not working when selectedRows is empty

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/sas-visualanalytics-thirdpartyvisualizations#48]
I have a ddc which filters another VA object through `messagingUtil.postSelectionMessage`.

I noticed that if the argument `selectedRows` contains at least one row, i.e. `selectedRows=[{row: 123}]`, the filter is applied correctly. 

However, if the `selectedRows` contains no rows, i.e. `selectedRows=[]` I would expect that the filtered VA object would receive no rows and hence show an empty area with the standard VA info message "no data selected ..."; instead, the filtered VA object receives ALL rows and doesn't filter at all, the very same behaviour like if I had set `selectedRows` to all original rows without excluding anything.

How can I send a `postSelectionMessage` to specify that no rows are selected and so every receiver must show no data?

**Comment by rluppi** [comment]
@gygabyte017 
This behavior is in compliance with how VA works. In VA, when you don't select anything, you are not applying any filter, therefore all rows are displayed. This happens with all VA objects, and Data-Driven Content object couldn't be different.

**Comment by gygabyte017** [comment]
I understand, thank you.

So is there no other way to let a VA object (linked to my ddc through Actions as a filter) display "no data" based on a condition that happens on the ddc?

**Comment by rluppi** [comment]
I'm afraid not. The opposite may be possible, though. If a VA object has a filter action defined to a DDC object, you can control via code what happens with the DDC when nothing is selected.
